FROM apache/spark:3.5.6

USER root

WORKDIR /app

COPY requirements-spark.txt .

RUN pip install --no-cache-dir -r requirements-spark.txt

COPY processing ./spark_processing

CMD ["/opt/spark/bin/spark-submit", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.6,org.apache.hadoop:hadoop-aws:3.3.4", "/app/spark_processing/spark_processing.py"]

