FROM python:3.11-slim

WORKDIR /app

COPY requirements_files/requirements-bronze.txt .

RUN pip install --no-cache-dir -r requirements-bronze.txt

COPY consumers ./consumers
COPY schemas ./schemas

CMD ["python", "-m", "consumers.minio_bronze_consumer"]